### ISSUE TITLE
1.15.2 Custom Rich Presence not working

### ISSUE THREAD

**Issue by Yamza** [Sunekaer/Simple-Discord-Rich-Presence#4]
I tried setting the art as suggested in issue#2 but it does not appear on discord. https://i.imgur.com/pGrw1Sl.png
https://i.imgur.com/pj4RezC.png

It's picking up the name only.

**Comment by Sunekaer** [comment]
Hmm remember "Due to caching, asset keys are not editable once they are saved. Delete and re-upload assets if you need to change a key name." And sometimes it takes a bit before images show up after they been upload.
If its still not working try and upload your config file and ill see if it works for me

**Comment by Yamza** [comment]
It actually is working now that I checked again. Sorry!
Seems it does take quite a long time for discord to sync up.
